### ISSUE TITLE
doesn't work on 17.0.1

### ISSUE THREAD

**Issue by mollyvita** [J-D-K/Avatool#11]
just launch avatool and press A. 
applet mode - crashes atmosphere with error code 2168-0002
title mode - crashes atmosphere with error code 2011-0301

**Comment by J-D-K** [comment]
I wrote it on that firmware so it does work. The only thing I can think of if it crashes 100% of the time is that there isn't any images on your SD, or I think I did change the SD card path to `sdmc:/avatars/` instead of `sdmc:/avatar`. Other than that, your mileage is always going to vary. It's always going to crash at some point.
